In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [4]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [8]:
movies.shape

(4803, 20)

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [12]:
# merging on the basis of 'title' because it is not feasible to work on two different dataset. Since "title" column is common in both, we can merge them on the basis of 'title'
movies.merge(credits,on='title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [11]:
 movies.merge(credits,on='title').shape

(4809, 23)

In [13]:
# we have to store this merged table in some variable and therefore we are merging and storing it in the 'movies' variable itself.
movies = movies.merge(credits,on='title')

In [14]:
movies.shape

(4809, 23)

Since we have 23 columns, we will remove those columns that are not necessary for our recommendation system. Below is the list of all those columns
which we are keeping
1. genres
2. id or movie_id
3. keywords
4. title       (we can also keep 'original_title' but we are not because original_title might have a title that is in a regional language)
5. overview

           (we can keep popularity column but since we are building a recommender system based on tags creation, this column will not fit in) 
7. cast        (because some people watch some movies just because of the actor) 
8. crew        (some people want to watch movies of a particular director, so crew is an important column)

In [15]:
movies[['movie_id','title','overview','genres','keywords','cast','crew']]
# storing these columns in 'movies' dataframe itself

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [16]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [17]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [18]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

Now the next step is that we will create a new dataframe that will have a new column 'tags' created by merging 'overview', 'genres', 'keywords', 'cast', 'crew'

In [20]:
# dropping the null values row because these are just 3 rows and its not a large value. won't make much impact on the recommendation if not there
movies.dropna(inplace = True)

In [21]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [22]:
movies.duplicated().sum()

0

In [24]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

The output is in weird format. It is a list of dictionaries.
We want the above output in the given format:
['Action','Adventure','Fantasy','Science Fiction']
For this we will create a helper function

def convert(obj):
    L = []               # creating a list
    for i in obj:
        L.append(i['name'])         # appending the value to the key 'name' from the dictionary to the list
    return L

In [28]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

TypeError: string indices must be integers, not 'str'

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

this is a string and that is why it is not working. So we first have to convert this string of list into list.
For this we have a module called ast in python which has a function literal_eval() which does this work.

In [27]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [29]:
# therefore I am creating the above function again which implements literal_eval() function
def convert(obj):
    L = []               # creating a list
    for i in ast.literal_eval(obj):
        L.append(i['name'])         # appending the value to the key 'name' from the dictionary to the list
    return L

In [30]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

the above function is working fine

In [31]:
movies['genres'].apply(convert)       # apply the convert function to the genres column of movies dataframe to convert list of dictionaries into list

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [32]:
# storing the above result in the same genres column
movies['genres'] = movies['genres'].apply(convert)

In [34]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

#### now we'll do the same thing in the 'keywords' column

In [35]:
movies.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [36]:
movies['keywords'].apply(convert)  # apply the convert function to the keywords column of movies dataframe to convert list of dictionaries into list

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [37]:
# storing the above result in the same keywords column
movies['keywords'] = movies['keywords'].apply(convert)

In [38]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [41]:
movies.iloc[0].cast         # or we can also use movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

###### here we will take top 3 actors and not all the cast

In [45]:
# {"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}
# in this "Jake Sully" is the name of character in the movie and "Sam Worthington" is the actual name of the actor
# therefore, we will take the the actual name. The same above function is repeated with some minor changes

def convert3(obj):
    L = []               # creating a list
    counter = 0            # to take maximum of 3 casts
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])         # appending the value to the key 'name' from the dictionary to the list
            counter+=1
        else:
            break
    return L

In [46]:
movies['cast'].apply(convert3)  # apply the convert function to the cast column of movies dataframe to get top 3 casts and to convert list of dictionaries into list

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [47]:
# storing the above result in the same cast column
movies['cast'] = movies['cast'].apply(convert3)

In [48]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [49]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

For us only those dictionaries matters where the values of job is director. So we'll make a function for this

In [50]:
def fetch_director(obj):
    L = []               # creating a list
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])         # appending the value to the key 'name' from the dictionary to the list
            break
    return L

In [52]:
movies['crew'].apply(fetch_director) # apply the convert function to the crew column of movies dataframe to fetch the directors and to convert list of dictionaries into list

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [53]:
# storing the above result in the same crew column
movies['crew'] = movies['crew'].apply(fetch_director)

In [54]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [55]:
# Now coming to the 'overview' column
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

Now this is a string. We will convert it into a list so that we can concatenate it with the other lists in the dataframe

In [56]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [57]:
# merging the above obtained lists into the same column
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [58]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

Now since these columns  ('overview', 'genres', 'keywords', 'cast', 'crew') are a list, we will concatenate them to make a big list and store them in a column called 'tags'. Then we'll convert this list in a string to make it a paragraph.

We have to remove spaces from ('genres', 'keywords', 'cast', 'crew') columns. For that we have to apply transformation on these columns.
For exammple, we have to convert 'Sam Worthington' to 'SamWorthington'

In [59]:
# first we'll try to apply this on genres column
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [61]:
# storing the above result in the same genres column
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [63]:
# now doing the same for remaining 3 columns
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [64]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]

In [65]:
# concatenating the above decided columns and forming a new column
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [66]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."

In [67]:
new_df = movies[['movie_id','title','tags']]

In [68]:
new_df.head(3)

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."

In [69]:
# now we'll convert the lists in tags column to string
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [70]:
# saving this in tags column
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\user\AppData\Local\Temp\ipykernel_6532\1942866522.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [71]:
new_df.head(3)

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...

In [72]:
# converting the string into lowercase
new_df['tags'].apply(lambda x:x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [73]:
# saving the result in the same column
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\user\AppData\Local\Temp\ipykernel_6532\2284866200.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [74]:
new_df.head(3)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...

# Vectorization
Here we will check the similarities between tags so that we could recommend similar movies.

For this, we will combine all the tags and create a large_text. For example, large_text = tag1 + tag2 + ..... +tag5000

Now, from this large_text, we will take out lets say 5000 most common words and create vectors with them.

We will use CountVectorizer from Sklearn.feature_extraction.text for this. Here we will use the stopwords functionality. Stopwords are the words which are used in the sentence formation. For example: are, is, in, the, etc.
We will neglect these stopwords

In [85]:
import nltk

In [86]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [87]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return" ".join(y)

In [99]:
stem('loved loving love')

'love love love'

In [100]:
stem('dance dancing danced')

'danc danc danc'

In [89]:
new_df['tags'].apply(stem)  # performing stemming

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [90]:
# storing the above result in the same column
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\user\AppData\Local\Temp\ipykernel_6532\3827281523.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

now to remove words which have similar meaning
for example ['loved','loving','love']    =>  ['love','love','love']
we will use stemming for this

we will use nltk library for this.


we have created a stem function above for this thing.

In [91]:
from sklearn.feature_extraction.text import CountVectorizer

In [92]:
cv = CountVectorizer(max_features=5000, stop_words='english')    # max_features=5000 these are the words taken out from large_text

In [93]:
cv.fit_transform(new_df['tags']).toarray()      # explicitly converting tags to numpy array as cv returns a sparse matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [94]:
# saving the above result in a new variable
vectors = cv.fit_transform(new_df['tags']).toarray()

In [95]:
vectors.shape

(4806, 5000)

In [96]:
# to check 5000 most frequent words
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

##### now we have 4806 vectors which have 5000 numbers each
##### we need to calculate the distance between each and every movie to each and every other movie 
##### the more the distance, lesser the similarity between those 2 movies
##### here we will not calculate the euclean distance, instead we will calculate the cosine distance
##### i.e., euclean distance is sqrt((x2-x1)^2 - (y2-y1)^2) and cosine distance is the angle between the two vectors
### Note: If you are working with high dimensional data, as in now as we have 4806x5000, euclean distance fails. It is not a reliable measure for higher dimensional data.

##### for cosine similarity, we have a function in sklearn.metrics.pairwise known as cosine_similarity which ranges between 0 to 1. If it is 1 then similarity is more else not.

In [102]:
from sklearn.metrics.pairwise import cosine_similarity

In [103]:
cosine_similarity(vectors)

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [104]:
cosine_similarity(vectors).shape

(4806, 4806)

In [125]:
# storing all these distances in a variable
similarity = cosine_similarity(vectors)

In [126]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

it has 4806 items as the distance is calculated between the 1st movie and all the other 4806 movies 
similarity[0].shape

In [127]:
# similarity score of 1st movie is 1 as it is the maximum similarity.. similarly it goes for 2nd movie
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

now the next step is to create a function which takes movie as an input and returns 5 similar movies.

To do this, first a movie is taken as input. Then we have to find the index of the movie in the data. Corresponding to that index, we will go to the similarity matrix which contains the distance of that movie with other movies. Then we will sort the similarity score in descending order i.e., more similar movies will come in the beginning. (more the similarity score, more similar the movie). Then we will fetch the top 5 movies and display them.

### this is how we will take out the index of the movie

In [128]:
new_df['title'] == 'Avatar'

0        True
1       False
2       False
3       False
4       False
        ...
4804    False
4805    False
4806    False
4807    False
4808    False
Name: title, Length: 4806, dtype: bool

In [129]:
new_df[new_df['title'] == 'Avatar']

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [130]:
new_df[new_df['title'] == 'Avatar'].index

Index([0], dtype='int64')

In [131]:
new_df[new_df['title'] == 'Avatar'].index[0]

0

In [135]:
new_df[new_df['title'] == 'Spectre'].index[0]

2

In [136]:
# this is how we'll fetch the similarity scores from similarity matrix.
similarity[new_df[new_df['title'] == 'Spectre'].index[0]]

array([0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
       0.        ])

In [144]:
# this is how we will sort the score
sorted(similarity[2],reverse = True)   # if we omit reverse attribute or write false in it then the sorting will be in ascending order

[0.9999999999999999,
 0.3609974361905776,
 0.3307189138830738,
 0.32639560491693337,
 0.2611164839335467,
 0.2390457218668787,
 0.22941573387056174,
 0.22645540682891913,
 0.22613350843332267,
 0.22592402852876595,
 0.220630652030457,
 0.21221867190679128,
 0.19094065395649332,
 0.18446619684315546,
 0.18042195912175807,
 0.17928429140015903,
 0.17817416127494956,
 0.17677669529663687,
 0.1735912687073534,
 0.171601618245911,
 0.17149858514250882,
 0.16984155512168936,
 0.16839382851364085,
 0.1670382761952652,
 0.16666666666666666,
 0.16413304107465318,
 0.16248342090492035,
 0.15811388300841897,
 0.15811388300841897,
 0.15811388300841894,
 0.1543033499620919,
 0.15386436372416593,
 0.15309310892394862,
 0.15231794896123557,
 0.15158476564770806,
 0.1507556722888818,
 0.1507556722888818,
 0.15006126199969522,
 0.1494035761667992,
 0.1494035761667992,
 0.14744195615489714,
 0.14731391274719738,
 0.147087101353638,
 0.147087101353638,
 0.14569287935358963,
 0.1453095484297741,
 0.14433756729740646,
 0.14433756729740646,
 0.1433848336691011,
 0.14301938838683884,
 0.1417366773784602,
 0.14153462926807447,
 0.1414213562373095,
 0.13927150363278887,
 0.13803940759355818,
 0.1369306393762915,
 0.13638618139749523,
 0.13608276348795434,
 0.13582634199860824,
 0.134790966504298,
 0.13363062095621217,
 0.1332504477222565,
 0.1332504477222565,
 0.13258252147247765,
 0.13130643285972254,
 0.13130643285972254,
 0.13130643285972254,
 0.13130643285972254,
 0.13032150878567172,
 0.12909944487358055,
 0.12892765578234916,
 0.12862393885688161,
 0.1270001270001905,
 0.1270001270001905,
 0.12626906806902632,
 0.12626906806902632,
 0.12626906806902632,
 0.125,
 0.125,
 0.12499999999999997,
 0.12499999999999997,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933274,
 0.12257258446136501,
 0.12247448713915887,
 0.12166606584807188,
 0.12166606584807188,
 0.12166606584807188,
 0.12166606584807188,
 0.12166606584807188,
 0.12141073279465801,
 0.12126781251816646,
 0.12028130608117202,
 0.12028130608117202,
 0.11962753722931604,
 0.11952286093343936,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11918282365569903,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.1181138978153835,
 0.1178511301977579,
 0.11713032141645455,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11572751247156893,
 0.11572751247156893,
 0.11507182723729042,
 0.11507182723729042,
 0.11507182723729042,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11410886614690958,
 0.11322770341445956,
 0.11322770341445956,
 0.11316968255314816,
 0.11306675421666135,
 0.11306675421666135,
 0.11306675421666135,
 0.11306675421666133,
 0.11225331376673431,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498947,
 0.11058146711617285,
 0.11058146711617285,
 0.11058146711617285,
 0.11058146711617285,
 0.11058146711617285,
 0.11048543456039804,
 0.11048543456039804,
 0.11043152607484653,
 0.11043152607484653,
 0.10963225241337865,
 0.1093987436234209,
 0.10910894511799618,
 0.10910894511799618,
 0.10910894511799618,
 0.10825317547305485,
 0.10825317547305485,
 0.10825317547305485,
 0.10798355319767,
 0.10783277320343841,
 0.10783277320343841,
 0.10783277320343841,
 0.10783277320343841,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10425720702853737,
 0.10425720702853737,
 0.10425720702853737,
 0.10400628679223047,
 0.10400628679223047,
 0.10400628679223047,
 0.10400628679223047,
 0.10400628679223047,
 0.103450736075296,
 0.103450736075296,
 0.10314212462587934,
 0.10314212462587934,
 0.10314212462587934,
 0.10274936706584831,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10159281922178943,
 0.10101525445522105,
 0.10101525445522105,
 0.10067340828210364,
 0.10022296571715913,
 0.10022296571715913,
 0.10022296571715913,
 0.10022296571715913,
 0.10008009612817945,
 0.09999999999999999,
 0.09847982464479191,
 0.09847982464479191,
 0.09847982464479191,
 0.09847982464479191,
 0.09847982464479191,
 0.09847982464479191,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09752368720068673,
 0.09712858623572641,
 0.09712858623572641,
 0.09712858623572641,
 0.09682458365518541,
 0.09682458365518541,
 0.09682458365518541,
 0.09682458365518541,
 0.09682458365518541,
 0.09682458365518541,
 0.09682458365518541,
 0.09682458365518541,
 0.09682458365518541,
 0.09622504486493762,
 0.09622504486493762,
 0.0958706236059213,
 0.09534625892455922,
 0.0953116064578779,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.0944911182523068,
 0.0944911182523068,
 0.0944911182523068,
 0.0944911182523068,
 0.0944911182523068,
 0.09422229518055111,
 0.09374999999999997,
 0.09374999999999997,
 0.09374999999999997,
 0.09374999999999997,
 0.09374999999999997,
 0.09365858115816939,
 0.09365858115816939,
 0.09284766908852592,
 0.09284766908852592,
 0.09284766908852592,
 0.09231861823449955,
 0.09231861823449955,
 0.09231861823449955,
 0.09231861823449955,
 0.09231861823449955,
 0.09231861823449955,
 0.09231861823449955,
 0.09231861823449955,
 0.09231861823449955,
 0.09205746178983235,
 0.09165444688834579,
 0.09128709291752767,
 0.09128709291752767,
 0.09128709291752767,
 0.09128709291752767,
 0.09128709291752767,
 0.09095085938862485,
 0.09095085938862485,
 0.09095085938862485,
 0.09095085938862485,
 0.09095085938862485,
 0.09095085938862485,
 0.09053574604251853,
 0.09053574604251853,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08908708063747478,
 0.08908708063747478,
 0.08908708063747478,
 0.08908708063747478,
 0.08908708063747478,
 0.08908708063747478,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08770580193070292,
 0.08770580193070292,
 0.08770580193070292,
 0.08751750525175062,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.086386842558136,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08451542547285165,
 0.08385254915624211,
 0.08385254915624211,
 0.08385254915624211,
 0.08385254915624211,
 0.08385254915624211,
 0.08385254915624211,
 0.0838525491562421,
 0.0835191380976326,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0828236445561349,
 0.0827605888602368,
 0.0827605888602368,
 0.08219949365267865,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.0808745799025788,
 0.0808745799025788,
 0.0808745799025788,
 0.0808745799025788,
 0.0808745799025788,
 0.08058229640253801,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.07955572841757301,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07856742013183861,
 0.07856742013183861,
 0.07819290527140303,
 0.07819290527140303,
 0.07819290527140303,
 0.07819290527140303,
 0.07819290527140303,
 0.07819290527140303,
 0.07819290527140303,
 0.07819290527140303,
 0.07819290527140303,
 0.07808688094430302,
 0.07808688094430302,
 0.07808688094430302,
 0.07808688094430302,
 0.07808688094430302,
 0.07761505257063328,
 0.0773565934694095,
 0.0773565934694095,
 0.0773565934694095,
 0.0773565934694095,
 0.0773565934694095,
 0.0773565934694095,
 0.0773565934694095,
 0.0773565934694095,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07654655446197431,
 0.07654655446197431,
 0.07654655446197431,
 0.07654655446197431,
 0.07654655446197431,
 0.07654655446197431,
 0.07654655446197431,
 0.07654655446197431,
 0.07654655446197431,
 0.07576144084141578,
 0.07576144084141578,
 0.07576144084141578,
 0.07576144084141578,
 0.07576144084141578,
 0.07576144084141578,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.075,
 0.075,
 0.075,
 0.075,
 0.075,
 0.07426106572325056,
 0.07426106572325056,
 0.07426106572325056,
 0.07426106572325056,
 0.07426106572325056,
 0.07426106572325056,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.073543550676819,
 0.073543550676819,
 0.073543550676819,
 0.073543550676819,
 0.073543550676819,
 0.073543550676819,
 0.073543550676819,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07284643967679481,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870323,
 0.07216878364870322,
 0.07216878364870322,
 0.07216878364870322,
 0.07216878364870322,
 0.07216878364870322,
 0.07169241683455055,
 0.07150969419341942,
 0.07150969419341942,
 0.07150969419341942,
 0.07150969419341942,
 0.07150969419341942,
 0.07150969419341942,
 0.0708683386892301,
 0.07086833868923009,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07035975447302918,
 0.07024393586862704,
 0.07024393586862704,
 0.06967330142916177,
 0.06963575181639443,
 0.06963575181639443,
 0.06963575181639443,
 0.06963575181639443,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06904309634237427,
 0.06904309634237427,
 0.06904309634237427,
 0.06904309634237427,
 0.06904309634237427,
 0.06904309634237427,
 0.06904309634237427,
 0.06904309634237427,
 0.06846531968814575,
 0.06846531968814575,
 0.06846531968814575,
 0.06846531968814575,
 0.06846531968814575,
 0.06846531968814575,
 0.06846531968814575,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.0679018095318889,
 0.0679018095318889,
 0.0679018095318889,
 0.0679018095318889,
 0.0679018095318889,
 0.0679018095318889,
 0.0679018095318889,
 0.0679018095318889,
 0.06735198826004059,
 0.06735198826004057,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06681531047810609,
 0.06629126073623882,
 0.06577935144802718,
 0.06577935144802718,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06565321642986127,
 0.06527912098338667,
 0.06527912098338667,
 0.06527912098338667,
 0.06527912098338667,
 0.06509445549041193,
 0.064790131918602,
 0.064790131918602,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06431196942844081,
 0.06431196942844081,
 0.06384423980690614,
 0.06384423980690614,
 0.06384423980690614,
 0.06384423980690614,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06338656910463875,
 0.06324555320336758,
 0.06293860187225167,
 0.06293860187225167,
 0.06293860187225167,
 0.06293860187225167,
 0.06293860187225167,
 0.06293860187225167,
 0.0625,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062499999999999986,
 0.062070441645177596,
 0.062070441645177596,
 0.061649620239508984,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.061237243569579436,
 0.061237243569579436,
 0.061237243569579436,
 0.06083303292403594,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.06063390625908323,
 0.060436722301903514,
 0.060436722301903514,
 0.060436722301903514,
 0.060436722301903514,
 0.060436722301903514,
 0.060048057676907664,
 0.060048057676907664,
 0.060048057676907664,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,
 0.059761430466719674,

In [145]:
# we have to hold the positions of distance as after sorting, the indexes will change and we won't be able to find out which score at which index belongs to which movie
# for this we will use enumerate() function which returns an object which when converted to list given the following result
list(enumerate(similarity[2]))

[(0, 0.08603090020146065),
 (1, 0.06063390625908323),
 (2, 0.9999999999999999),
 (3, 0.060048057676907664),
 (4, 0.0773565934694095),
 (5, 0.07086833868923009),
 (6, 0.02192645048267573),
 (7, 0.1332504477222565),
 (8, 0.06454972243679027),
 (9, 0.10540925533894598),
 (10, 0.08385254915624211),
 (11, 0.3609974361905776),
 (12, 0.06565321642986127),
 (13, 0.049029033784546004),
 (14, 0.05590169943749474),
 (15, 0.06846531968814575),
 (16, 0.057353933467640436),
 (17, 0.15231794896123557),
 (18, 0.0827605888602368),
 (19, 0.0679018095318889),
 (20, 0.03162277660168379),
 (21, 0.059761430466719674),
 (22, 0.036084391824351615),
 (23, 0.1270001270001905),
 (24, 0.058123819371909635),
 (25, 0.0),
 (26, 0.11180339887498948),
 (27, 0.0679018095318889),
 (28, 0.09525009525014289),
 (29, 0.3307189138830738),
 (30, 0.07284643967679481),
 (31, 0.06933752452815364),
 (32, 0.04642383454426296),
 (33, 0.07071067811865475),
 (34, 0.0),
 (35, 0.07216878364870323),
 (36, 0.10783277320343841),
 (37, 0.028676966733820218),
 (38, 0.11048543456039804),
 (39, 0.059761430466719674),
 (40, 0.08385254915624211),
 (41, 0.0773565934694095),
 (42, 0.0),
 (43, 0.04950737714883371),
 (44, 0.036860489038724284),
 (45, 0.02245066275334686),
 (46, 0.15158476564770806),
 (47, 0.08574929257125441),
 (48, 0.06904309634237427),
 (49, 0.031750031750047626),
 (50, 0.12309149097933274),
 (51, 0.08770580193070292),
 (52, 0.053916386601719206),
 (53, 0.04682929057908469),
 (54, 0.034020690871988585),
 (55, 0.03834824944236852),
 (56, 0.11306675421666135),
 (57, 0.0),
 (58, 0.147087101353638),
 (59, 0.039528470752104736),
 (60, 0.040032038451271776),
 (61, 0.07216878364870323),
 (62, 0.1369306393762915),
 (63, 0.08908708063747478),
 (64, 0.0),
 (65, 0.06384423980690614),
 (66, 0.024514516892273002),
 (67, 0.08964214570007951),
 (68, 0.06565321642986127),
 (69, 0.04330127018922193),
 (70, 0.05521576303742327),
 (71, 0.053300179088902604),
 (72, 0.08964214570007951),
 (73, 0.0),
 (74, 0.049029033784546004),
 (75, 0.05661385170722978),
 (76, 0.10425720702853737),
 (77, 0.0),
 (78, 0.0828236445561349),
 (79, 0.045267873021259265),
 (80, 0.03666177875533832),
 (81, 0.060048057676907664),
 (82, 0.05521576303742327),
 (83, 0.073543550676819),
 (84, 0.06735198826004059),
 (85, 0.053300179088902604),
 (86, 0.025785531156469834),
 (87, 0.06063390625908323),
 (88, 0.13130643285972254),
 (89, 0.03137279025690793),
 (90, 0.03340765523905304),
 (91, 0.06063390625908323),
 (92, 0.045267873021259265),
 (93, 0.025785531156469834),
 (94, 0.10206207261596575),
 (95, 0.05103103630798288),
 (96, 0.05590169943749474),
 (97, 0.07576144084141578),
 (98, 0.05455447255899809),
 (99, 0.058123819371909635),
 (100, 0.0),
 (101, 0.05590169943749474),
 (102, 0.045267873021259265),
 (103, 0.06527912098338667),
 (104, 0.06063390625908323),
 (105, 0.1507556722888818),
 (106, 0.022633936510629633),
 (107, 0.04490132550669372),
 (108, 0.15811388300841897),
 (109, 0.07071067811865475),
 (110, 0.0),
 (111, 0.05455447255899809),
 (112, 0.05590169943749474),
 (113, 0.0236227795630767),
 (114, 0.024999999999999998),
 (115, 0.04767312946227961),
 (116, 0.05270462766947299),
 (117, 0.06454972243679027),
 (118, 0.0),
 (119, 0.0944911182523068),
 (120, 0.02551551815399144),
 (121, 0.09095085938862485),
 (122, 0.06350006350009525),
 (123, 0.073543550676819),
 (124, 0.049029033784546004),
 (125, 0.04273521617236423),
 (126, 0.08718572905786445),
 (127, 0.07955572841757301),
 (128, 0.05892556509887895),
 (129, 0.12626906806902632),
 (130, 0.029462782549439476),
 (131, 0.08603090020146065),
 (132, 0.024514516892273002),
 (133, 0.0),
 (134, 0.1414213562373095),
 (135, 0.0),
 (136, 0.02551551815399144),
 (137, 0.06565321642986127),
 (138, 0.08385254915624211),
 (139, 0.10963225241337865),
 (140, 0.073543550676819),
 (141, 0.031750031750047626),
 (142, 0.06154574548966637),
 (143, 0.0472455591261534),
 (144, 0.05455447255899809),
 (145, 0.020979533957417223),
 (146, 0.0),
 (147, 0.21221867190679128),
 (148, 0.035355339059327376),
 (149, 0.042257712736425826),
 (150, 0.05966679631317975),
 (151, 0.11058146711617285),
 (152, 0.12126781251816646),
 (153, 0.08574929257125441),
 (154, 0.03340765523905304),
 (155, 0.06681531047810609),
 (156, 0.021759706994462225),
 (157, 0.07216878364870323),
 (158, 0.07284643967679481),
 (159, 0.03466876226407682),
 (160, 0.1093987436234209),
 (161, 0.0),
 (162, 0.07216878364870323),
 (163, 0.0828236445561349),
 (164, 0.11624763874381927),
 (165, 0.049999999999999996),
 (166, 0.19094065395649332),
 (167, 0.09847982464479191),
 (168, 0.08183170883849714),
 (169, 0.04811252243246881),
 (170, 0.16248342090492035),
 (171, 0.024753688574416854),
 (172, 0.03857583749052298),
 (173, 0.0),
 (174, 0.11322770341445956),
 (175, 0.05157106231293967),
 (176, 0.06350006350009525),
 (177, 0.0),
 (178, 0.053300179088902604),
 (179, 0.07905694150420947),
 (180, 0.12028130608117202),
 (181, 0.024514516892273002),
 (182, 0.07654655446197431),
 (183, 0.0958706236059213),
 (184, 0.0),
 (185, 0.027607881518711633),
 (186, 0.08574929257125441),
 (187, 0.11180339887498947),
 (188, 0.09622504486493762),
 (189, 0.041666666666666664),
 (190, 0.11507182723729042),
 (191, 0.026650089544451302),
 (192, 0.025785531156469834),
 (193, 0.05151021148075838),
 (194, 0.0),
 (195, 0.03227486121839514),
 (196, 0.02830692585361489),
 (197, 0.060436722301903514),
 (198, 0.062499999999999986),
 (199, 0.0472455591261534),
 (200, 0.07905694150420947),
 (201, 0.07216878364870323),
 (202, 0.06804138174397717),
 (203, 0.06063390625908323),
 (204, 0.053916386601719206),
 (205, 0.12166606584807188),
 (206, 0.060436722301903514),
 (207, 0.11180339887498948),
 (208, 0.06681531047810609),
 (209, 0.07372097807744857),
 (210, 0.10910894511799618),
 (211, 0.0),
 (212, 0.04811252243246881),
 (213, 0.06431196942844081),
 (214, 0.0),
 (215, 0.07216878364870322),
 (216, 0.07071067811865475),
 (217, 0.02321191727213148),
 (218, 0.16666666666666666),
 (219, 0.10022296571715913),
 (220, 0.06454972243679027),
 (221, 0.05157106231293967),
 (222, 0.021759706994462225),
 (223, 0.08492077756084468),
 (224, 0.044194173824159216),
 (225, 0.02551551815399144),
 (226, 0.032826608214930636),
 (227, 0.17928429140015903),
 (228, 0.07216878364870322),
 (229, 0.11713032141645455),
 (230, 0.040032038451271776),
 (231, 0.02551551815399144),
 (232, 0.06063390625908323),
 (233, 0.0753778361444409),
 (234, 0.04682929057908469),
 (235, 0.027607881518711633),
 (236, 0.062499999999999986),
 (237, 0.07216878364870323),
 (238, 0.04029114820126901),
 (239, 0.0),
 (240, 0.05103103630798288),
 (241, 0.11470786693528087),
 (242, 0.05892556509887895),
 (243, 0.07576144084141578),
 (244, 0.03340765523905304),
 (245, 0.1178511301977579),
 (246, 0.0413802944301184),
 (247, 0.06565321642986127),
 (248, 0.09712858623572641),
 (249, 0.11306675421666135),
 (250, 0.0),
 (251, 0.0),
 (252, 0.11048543456039804),
 (253, 0.06846531968814575),
 (254, 0.025253813613805264),
 (255, 0.027277236279499045),
 (256, 0.12166606584807188),
 (257, 0.029061909685954818),
 (258, 0.01928791874526149),
 (259, 0.06681531047810609),
 (260, 0.09525009525014289),
 (261, 0.07905694150420949),
 (262, 0.06963575181639443),
 (263, 0.10606601717798213),
 (264, 0.0),
 (265, 0.0),
 (266, 0.053916386601719206),
 (267, 0.10606601717798213),
 (268, 0.057353933467640436),
 (269, 0.03227486121839514),
 (270, 0.07216878364870322),
 (271, 0.05157106231293967),
 (272, 0.0),
 (273, 0.06904309634237427),
 (274, 0.0838525491562421),
 (275, 0.062499999999999986),
 (276, 0.034020690871988585),
 (277, 0.1735912687073534),
 (278, 0.05103103630798288),
 (279, 0.05050762722761053),
 (280, 0.05661385170722978),
 (281, 0.0472455591261534),
 (282, 0.14569287935358963),
 (283, 0.059761430466719674),
 (284, 0.0),
 (285, 0.06384423980690614),
 (286, 0.04256282653793742),
 (287, 0.02830692585361489),
 (288, 0.059761430466719674),
 (289, 0.024999999999999998),
 (290, 0.06933752452815364),
 (291, 0.08183170883849714),
 (292, 0.09682458365518541),
 (293, 0.03227486121839514),
 (294, 0.12499999999999997),
 (295, 0.028676966733820218),
 (296, 0.021128856368212913),
 (297, 0.04811252243246881),
 (298, 0.026064301757134343),
 (299, 0.043193421279068),
 (300, 0.053300179088902604),
 (301, 0.061237243569579436),
 (302, 0.025253813613805264),
 (303, 0.06063390625908323),
 (304, 0.07169241683455055),
 (305, 0.06904309634237427),
 (306, 0.029462782549439476),
 (307, 0.10159281922178943),
 (308, 0.07372097807744857),
 (309, 0.034020690871988585),
 (310, 0.0835191380976326),
 (311, 0.027277236279499045),
 (312, 0.05455447255899809),
 (313, 0.0),
 (314, 0.0944911182523068),
 (315, 0.06063390625908323),
 (316, 0.021596710639534),
 (317, 0.0),
 (318, 0.0),
 (319, 0.036084391824351615),
 (320, 0.06681531047810609),
 (321, 0.03857583749052298),
 (322, 0.057353933467640436),
 (323, 0.0),
 (324, 0.026650089544451302),
 (325, 0.10825317547305485),
 (326, 0.0),
 (327, 0.0),
 (328, 0.029880715233359837),
 (329, 0.11470786693528087),
 (330, 0.08183170883849714),
 (331, 0.024514516892273002),
 (332, 0.11624763874381927),
 (333, 0.0),
 (334, 0.05270462766947299),
 (335, 0.025253813613805264),
 (336, 0.03768891807222045),
 (337, 0.04950737714883371),
 (338, 0.036084391824351615),
 (339, 0.0799502686333539),
 (340, 0.053916386601719206),
 (341, 0.029880715233359837),
 (342, 0.05856516070822727),
 (343, 0.0),
 (344, 0.03227486121839514),
 (345, 0.049999999999999996),
 (346, 0.029880715233359837),
 (347, 0.0),
 (348, 0.03340765523905304),
 (349, 0.05521576303742327),
 (350, 0.10660035817780521),
 (351, 0.04950737714883371),
 (352, 0.029880715233359837),
 (353, 0.02245066275334686),
 (354, 0.0944911182523068),
 (355, 0.05966679631317975),
 (356, 0.13130643285972254),
 (357, 0.0),
 (358, 0.032826608214930636),
 (359, 0.034020690871988585),
 (360, 0.0),
 (361, 0.027277236279499045),
 (362, 0.03466876226407682),
 (363, 0.043193421279068),
 (364, 0.0),
 (365, 0.05455447255899809),
 (366, 0.030772872744833184),
 (367, 0.11058146711617285),
 (368, 0.07071067811865475),
 (369, 0.08385254915624211),
 (370, 0.11043152607484653),
 (371, 0.10425720702853737),
 (372, 0.12892765578234916),
 (373, 0.0),
 (374, 0.0413802944301184),
 (375, 0.0),
 (376, 0.02551551815399144),
 (377, 0.05050762722761053),
 (378, 0.0),
 (379, 0.036860489038724284),
 (380, 0.0),
 (381, 0.04564354645876383),
 (382, 0.0),
 (383, 0.0472455591261534),
 (384, 0.062499999999999986),
 (385, 0.0),
 (386, 0.09534625892455922),
 (387, 0.025785531156469834),
 (388, 0.024999999999999998),
 (389, 0.06350006350009525),
 (390, 0.0),
 (391, 0.0),
 (392, 0.06565321642986127),
 (393, 0.0),
 (394, 0.0808745799025788),
 (395, 0.0),
 (396, 0.07150969419341942),
 (397, 0.0),
 (398, 0.024056261216234404),
 (399, 0.05157106231293967),
 (400, 0.09847982464479191),
 (401, 0.034020690871988585),
 (402, 0.08492077756084468),
 (403, 0.0679018095318889),
 (404, 0.0),
 (405, 0.06063390625908323),
 (406, 0.0),
 (407, 0.0),
 (408, 0.035355339059327376),
 (409, 0.0),
 (410, 0.053300179088902604),
 (411, 0.057353933467640436),
 (412, 0.07819290527140303),
 (413, 0.030772872744833184),
 (414, 0.03227486121839514),
 (415, 0.01940376314265832),
 (416, 0.0),
 (417, 0.0),
 (418, 0.11572751247156893),
 (419, 0.075),
 (420, 0.049029033784546004),
 (421, 0.05050762722761053),
 (422, 0.031750031750047626),
 (423, 0.0),
 (424, 0.04055535528269063),
 (425, 0.09284766908852592),
 (426, 0.07808688094430302),
 (427, 0.028676966733820218),
 (428, 0.020277677641345315),
 (429, 0.0),
 (430, 0.0),
 (431, 0.0),
 (432, 0.04950737714883371),
 (433, 0.06804138174397717),
 (434, 0.0),
 (435, 0.03857583749052298),
 (436, 0.0),
 (437, 0.11180339887498948),
 (438, 0.0),
 (439, 0.028676966733820218),
 (440, 0.0),
 (441, 0.0),
 (442, 0.04950737714883371),
 (443, 0.0),
 (444, 0.07654655446197431),
 (445, 0.0),
 (446, 0.05050762722761053),
 (447, 0.04682929057908469),
 (448, 0.0),
 (449, 0.059761430466719674),
 (450, 0.0),
 (451, 0.05455447255899809),
 (452, 0.0),
 (453, 0.053300179088902604),
 (454, 0.0),
 (455, 0.06629126073623882),
 (456, 0.0236227795630767),
 (457, 0.09374999999999997),
 (458, 0.0472455591261534),
 (459, 0.03768891807222045),
 (460, 0.0),
 (461, 0.030772872744833184),
 (462, 0.017589938618257295),
 (463, 0.0),
 (464, 0.0),
 (465, 0.041666666666666664),
 (466, 0.11858541225631421),
 (467, 0.04602873089491617),
 (468, 0.09095085938862485),
 (469, 0.064790131918602),
 (470, 0.0),
 (471, 0.04642383454426296),
 (472, 0.058123819371909635),
 (473, 0.0),
 (474, 0.029880715233359837),
 (475, 0.04767312946227961),
 (476, 0.07372097807744857),
 (477, 0.0),
 (478, 0.039283710065919304),
 (479, 0.01917412472118426),
 (480, 0.053300179088902604),
 (481, 0.025785531156469834),
 (482, 0.0),
 (483, 0.10206207261596575),
 (484, 0.031750031750047626),
 (485, 0.028676966733820218),
 (486, 0.05225497607187132),
 (487, 0.06933752452815364),
 (488, 0.01813690625275029),
 (489, 0.0),
 (490, 0.07715167498104596),
 (491, 0.043193421279068),
 (492, 0.05521576303742327),
 (493, 0.0),
 (494, 0.0),
 (495, 0.06933752452815364),
 (496, 0.01853123291652753),
 (497, 0.035355339059327376),
 (498, 0.11058146711617285),
 (499, 0.0),
 (500, 0.05661385170722978),
 (501, 0.04454354031873739),
 (502, 0.024282146558931603),
 (503, 0.08183170883849714),
 (504, 0.0),
 (505, 0.07372097807744857),
 (506, 0.03768891807222045),
 (507, 0.06963575181639443),
 (508, 0.13803940759355818),
 (509, 0.024056261216234404),
 (510, 0.026958193300859603),
 (511, 0.06681531047810609),
 (512, 0.08964214570007951),
 (513, 0.053916386601719206),
 (514, 0.0808745799025788),
 (515, 0.0),
 (516, 0.0),
 (517, 0.04351941398892445),
 (518, 0.04767312946227961),
 (519, 0.05590169943749474),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.07905694150420949),
 (524, 0.0),
 (525, 0.05157106231293967),
 (526, 0.0),
 (527, 0.036084391824351615),
 (528, 0.04856429311786321),
 (529, 0.052128603514268686),
 (530, 0.06063390625908323),
 (531, 0.10101525445522105),
 (532, 0.0),
 (533, 0.032826608214930636),
 (534, 0.09128709291752767),
 (535, 0.053300179088902604),
 (536, 0.024514516892273002),
 (537, 0.036860489038724284),
 (538, 0.032826608214930636),
 (539, 0.06063390625908323),
 (540, 0.05455447255899809),
 (541, 0.023014365447458086),
 (542, 0.020145574100634504),
 (543, 0.0773565934694095),
 (544, 0.09095085938862485),
 (545, 0.0),
 (546, 0.03466876226407682),
 (547, 0.030316953129541614),
 (548, 0.057353933467640436),
 (549, 0.026064301757134343),
 (550, 0.0),
 (551, 0.02054987341316966),
 (552, 0.030772872744833184),
 (553, 0.031249999999999993),
 (554, 0.0),
 (555, 0.0),
 (556, 0.029061909685954818),
 (557, 0.0799502686333539),
 (558, 0.0),
 (559, 0.0),
 (560, 0.019641855032959652),
 (561, 0.06933752452815364),
 (562, 0.06681531047810609),
 (563, 0.0),
 (564, 0.0),
 (565, 0.0236227795630767),
 (566, 0.026064301757134343),
 (567, 0.0),
 (568, 0.06154574548966637),
 (569, 0.05157106231293967),
 (570, 0.036860489038724284),
 (571, 0.04602873089491617),
 (572, 0.04682929057908469),
 (573, 0.0679018095318889),
 (574, 0.07654655446197431),
 (575, 0.0),
 (576, 0.0),
 (577, 0.09231861823449955),
 (578, 0.020412414523193145),
 (579, 0.09525009525014289),
 (580, 0.10540925533894598),
 (581, 0.06350006350009525),
 (582, 0.07284643967679481),
 (583, 0.02054987341316966),
 (584, 0.0),
 (585, 0.053300179088902604),
 (586, 0.049029033784546004),
 (587, 0.0773565934694095),
 (588, 0.02795084971874737),
 (589, 0.08451542547285165),
 (590, 0.09847982464479191),
 (591, 0.06846531968814575),
 (592, 0.023014365447458086),
 (593, 0.062070441645177596),
 (594, 0.0808745799025788),
 (595, 0.049999999999999996),
 (596, 0.12626906806902632),
 (597, 0.03227486121839514),
 (598, 0.0),
 (599, 0.014940357616679919),
 (600, 0.075),
 (601, 0.018233123937236816),
 (602, 0.04950737714883371),
 (603, 0.05892556509887895),
 (604, 0.07216878364870323),
 (605, 0.0),
 (606, 0.029061909685954818),
 (607, 0.06293860187225167),
 (608, 0.032826608214930636),
 (609, 0.05103103630798288),
 (610, 0.06324555320336758),
 (611, 0.07576144084141578),
 (612, 0.04602873089491617),
 (613, 0.07715167498104596),
 (614, 0.0),
 (615, 0.06681531047810609),
 (616, 0.03768891807222045),
 (617, 0.027277236279499045),
 (618, 0.04811252243246881),
 (619, 0.0),
 (620, 0.03768891807222045),
 (621, 0.035355339059327376),
 (622, 0.04602873089491617),
 (623, 0.024514516892273002),
 (624, 0.03768891807222045),
 (625, 0.0),
 (626, 0.059761430466719674),
 (627, 0.07905694150420947),
 (628, 0.0),
 (629, 0.07905694150420949),
 (630, 0.0),
 (631, 0.027607881518711633),
 (632, 0.05590169943749474),
 (633, 0.04856429311786321),
 (634, 0.053916386601719206),
 (635, 0.0),
 (636, 0.05103103630798288),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.06527912098338667),
 (641, 0.0),
 (642, 0.031750031750047626),
 (643, 0.05455447255899809),
 (644, 0.05455447255899809),
 (645, 0.07216878364870322),
 (646, 0.0),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.023414645289542346),
 (653, 0.07905694150420947),
 (654, 0.11316968255314816),
 (655, 0.026064301757134343),
 (656, 0.0),
 (657, 0.0753778361444409),
 (658, 0.026352313834736494),
 (659, 0.0828236445561349),
 (660, 0.06804138174397717),
 (661, 0.04564354645876383),
 (662, 0.0),
 (663, 0.031750031750047626),
 (664, 0.06565321642986127),
 (665, 0.07426106572325056),
 (666, 0.0),
 (667, 0.031249999999999993),
 (668, 0.036860489038724284),
 (669, 0.03857583749052298),
 (670, 0.01906232129157558),
 (671, 0.024753688574416854),
 (672, 0.030772872744833184),
 (673, 0.06527912098338667),
 (674, 0.025785531156469834),
 (675, 0.024514516892273002),
 (676, 0.031249999999999993),
 (677, 0.10910894511799618),
 (678, 0.09525009525014289),
 (679, 0.0206901472150592),
 (680, 0.08183170883849714),
 (681, 0.0),
 (682, 0.0),
 (683, 0.10540925533894598),
 (684, 0.035355339059327376),
 (685, 0.035355339059327376),
 (686, 0.0),
 (687, 0.11322770341445956),
 (688, 0.0),
 (689, 0.027607881518711633),
 (690, 0.05455447255899809),
 (691, 0.06454972243679027),
 (692, 0.0),
 (693, 0.036860489038724284),
 (694, 0.07150969419341942),
 (695, 0.14433756729740646),
 (696, 0.09365858115816939),
 (697, 0.0),
 (698, 0.1417366773784602),
 (699, 0.0),
 (700, 0.062499999999999986),
 (701, 0.031249999999999993),
 (702, 0.073543550676819),
 (703, 0.0),
 (704, 0.024753688574416854),
 (705, 0.0),
 (706, 0.0236227795630767),
 (707, 0.0),
 (708, 0.10783277320343841),
 (709, 0.0),
 (710, 0.0),
 (711, 0.11470786693528087),
 (712, 0.026352313834736494),
 (713, 0.0),
 (714, 0.057353933467640436),
 (715, 0.07216878364870323),
 (716, 0.029462782549439476),
 (717, 0.04767312946227961),
 (718, 0.049029033784546004),
 (719, 0.0),
 (720, 0.0),
 (721, 0.10606601717798213),
 (722, 0.0),
 (723, 0.026650089544451302),
 (724, 0.10314212462587934),
 (725, 0.0),
 (726, 0.032826608214930636),
 (727, 0.033557802760701215),
 (728, 0.026352313834736494),
 (729, 0.0),
 (730, 0.03296902366978935),
 (731, 0.08492077756084468),
 (732, 0.04950737714883371),
 (733, 0.022271770159368695),
 (734, 0.04856429311786321),
 (735, 0.07284643967679481),
 (736, 0.03227486121839514),
 (737, 0.05590169943749474),
 (738, 0.0),
 (739, 0.08333333333333333),
 (740, 0.0472455591261534),
 (741, 0.09095085938862485),
 (742, 0.032826608214930636),
 (743, 0.0),
 (744, 0.035355339059327376),
 (745, 0.06350006350009525),
 (746, 0.07024393586862704),
 (747, 0.06431196942844081),
 (748, 0.039528470752104736),
 (749, 0.0),
 (750, 0.09284766908852592),
 (751, 0.10400628679223047),
 (752, 0.0),
 (753, 0.11952286093343935),
 (754, 0.027277236279499045),
 (755, 0.0827605888602368),
 (756, 0.031249999999999993),
 (757, 0.05270462766947299),
 (758, 0.07426106572325056),
 (759, 0.025253813613805264),
 (760, 0.029061909685954818),
 (761, 0.062499999999999986),
 (762, 0.06454972243679027),
 (763, 0.0),
 (764, 0.0),
 (765, 0.0),
 (766, 0.0),
 (767, 0.07654655446197431),
 (768, 0.022271770159368695),
 (769, 0.034020690871988585),
 (770, 0.023414645289542346),
 (771, 0.0),
 (772, 0.0),
 (773, 0.10400628679223047),

In [148]:
# now we can sort the above data
sorted(list(enumerate(similarity[2])),reverse=True,key=lambda x:x[1])    # if key was not written, sorting would have been done on the basis of index values

[(2, 0.9999999999999999),
 (11, 0.3609974361905776),
 (29, 0.3307189138830738),
 (1344, 0.32639560491693337),
 (4075, 0.2611164839335467),
 (1745, 0.2390457218668787),
 (3338, 0.22941573387056174),
 (3164, 0.22645540682891913),
 (1719, 0.22613350843332267),
 (1132, 0.22592402852876595),
 (4343, 0.220630652030457),
 (147, 0.21221867190679128),
 (166, 0.19094065395649332),
 (3253, 0.18446619684315546),
 (3287, 0.18042195912175807),
 (227, 0.17928429140015903),
 (1101, 0.17817416127494956),
 (4641, 0.17677669529663687),
 (277, 0.1735912687073534),
 (1201, 0.171601618245911),
 (4008, 0.17149858514250882),
 (1715, 0.16984155512168936),
 (1085, 0.16839382851364085),
 (1839, 0.1670382761952652),
 (218, 0.16666666666666666),
 (972, 0.16413304107465318),
 (170, 0.16248342090492035),
 (108, 0.15811388300841897),
 (3353, 0.15811388300841897),
 (2923, 0.15811388300841894),
 (3973, 0.1543033499620919),
 (973, 0.15386436372416593),
 (4697, 0.15309310892394862),
 (17, 0.15231794896123557),
 (46, 0.15158476564770806),
 (105, 0.1507556722888818),
 (2749, 0.1507556722888818),
 (1771, 0.15006126199969522),
 (2165, 0.1494035761667992),
 (3345, 0.1494035761667992),
 (1192, 0.14744195615489714),
 (3496, 0.14731391274719738),
 (58, 0.147087101353638),
 (2671, 0.147087101353638),
 (282, 0.14569287935358963),
 (1235, 0.1453095484297741),
 (695, 0.14433756729740646),
 (1083, 0.14433756729740646),
 (1078, 0.1433848336691011),
 (2676, 0.14301938838683884),
 (698, 0.1417366773784602),
 (3620, 0.14153462926807447),
 (134, 0.1414213562373095),
 (2360, 0.13927150363278887),
 (508, 0.13803940759355818),
 (62, 0.1369306393762915),
 (1365, 0.13638618139749523),
 (2648, 0.13608276348795434),
 (939, 0.13582634199860824),
 (2391, 0.134790966504298),
 (3768, 0.13363062095621217),
 (7, 0.1332504477222565),
 (2052, 0.1332504477222565),
 (2328, 0.13258252147247765),
 (88, 0.13130643285972254),
 (356, 0.13130643285972254),
 (1002, 0.13130643285972254),
 (3354, 0.13130643285972254),
 (1934, 0.13032150878567172),
 (1025, 0.12909944487358055),
 (372, 0.12892765578234916),
 (3719, 0.12862393885688161),
 (23, 0.1270001270001905),
 (3261, 0.1270001270001905),
 (129, 0.12626906806902632),
 (596, 0.12626906806902632),
 (1533, 0.12626906806902632),
 (1588, 0.125),
 (1617, 0.125),
 (294, 0.12499999999999997),
 (1699, 0.12499999999999997),
 (50, 0.12309149097933274),
 (2492, 0.12309149097933274),
 (4406, 0.12309149097933274),
 (1441, 0.12257258446136501),
 (3145, 0.12247448713915887),
 (205, 0.12166606584807188),
 (256, 0.12166606584807188),
 (808, 0.12166606584807188),
 (1282, 0.12166606584807188),
 (3728, 0.12166606584807188),
 (2076, 0.12141073279465801),
 (152, 0.12126781251816646),
 (180, 0.12028130608117202),
 (1672, 0.12028130608117202),
 (2297, 0.11962753722931604),
 (3426, 0.11952286093343936),
 (753, 0.11952286093343935),
 (859, 0.11952286093343935),
 (1509, 0.11952286093343935),
 (3138, 0.11952286093343935),
 (2400, 0.11918282365569903),
 (466, 0.11858541225631421),
 (2293, 0.11858541225631421),
 (2997, 0.11858541225631421),
 (3861, 0.11858541225631421),
 (2048, 0.1181138978153835),
 (245, 0.1178511301977579),
 (229, 0.11713032141645455),
 (164, 0.11624763874381927),
 (332, 0.11624763874381927),
 (2679, 0.11624763874381927),
 (418, 0.11572751247156893),
 (1666, 0.11572751247156893),
 (190, 0.11507182723729042),
 (1303, 0.11507182723729042),
 (1459, 0.11507182723729042),
 (241, 0.11470786693528087),
 (329, 0.11470786693528087),
 (711, 0.11470786693528087),
 (1176, 0.11470786693528087),
 (1917, 0.11470786693528087),
 (2756, 0.11410886614690958),
 (174, 0.11322770341445956),
 (687, 0.11322770341445956),
 (654, 0.11316968255314816),
 (56, 0.11306675421666135),
 (249, 0.11306675421666135),
 (2554, 0.11306675421666135),
 (3053, 0.11306675421666133),
 (1392, 0.11225331376673431),
 (26, 0.11180339887498948),
 (207, 0.11180339887498948),
 (437, 0.11180339887498948),
 (1084, 0.11180339887498948),
 (1376, 0.11180339887498948),
 (2746, 0.11180339887498948),
 (3023, 0.11180339887498948),
 (3150, 0.11180339887498948),
 (187, 0.11180339887498947),
 (151, 0.11058146711617285),
 (367, 0.11058146711617285),
 (498, 0.11058146711617285),
 (1882, 0.11058146711617285),
 (2758, 0.11058146711617285),
 (38, 0.11048543456039804),
 (252, 0.11048543456039804),
 (370, 0.11043152607484653),
 (952, 0.11043152607484653),
 (139, 0.10963225241337865),
 (160, 0.1093987436234209),
 (210, 0.10910894511799618),
 (677, 0.10910894511799618),
 (986, 0.10910894511799618),
 (325, 0.10825317547305485),
 (1152, 0.10825317547305485),
 (2246, 0.10825317547305485),
 (2545, 0.10798355319767),
 (36, 0.10783277320343841),
 (708, 0.10783277320343841),
 (2004, 0.10783277320343841),
 (3671, 0.10783277320343841),
 (350, 0.10660035817780521),
 (1363, 0.10660035817780521),
 (1397, 0.10660035817780521),
 (3182, 0.10660035817780521),
 (3593, 0.10660035817780521),
 (3612, 0.10660035817780521),
 (4146, 0.10660035817780521),
 (263, 0.10606601717798213),
 (267, 0.10606601717798213),
 (721, 0.10606601717798213),
 (783, 0.10606601717798213),
 (1074, 0.10606601717798213),
 (1723, 0.10606601717798213),
 (2917, 0.10606601717798213),
 (4472, 0.10606601717798213),
 (4623, 0.10606601717798213),
 (9, 0.10540925533894598),
 (580, 0.10540925533894598),
 (683, 0.10540925533894598),
 (1295, 0.10540925533894598),
 (76, 0.10425720702853737),
 (371, 0.10425720702853737),
 (3233, 0.10425720702853737),
 (751, 0.10400628679223047),
 (773, 0.10400628679223047),
 (2279, 0.10400628679223047),
 (4271, 0.10400628679223047),
 (4509, 0.10400628679223047),
 (2082, 0.103450736075296),
 (4046, 0.103450736075296),
 (724, 0.10314212462587934),
 (831, 0.10314212462587934),
 (1644, 0.10314212462587934),
 (2001, 0.10274936706584831),
 (94, 0.10206207261596575),
 (483, 0.10206207261596575),
 (1094, 0.10206207261596575),
 (1274, 0.10206207261596575),
 (1613, 0.10206207261596575),
 (1717, 0.10206207261596575),
 (2003, 0.10206207261596575),
 (2091, 0.10206207261596575),
 (2646, 0.10206207261596575),
 (3227, 0.10206207261596575),
 (3718, 0.10206207261596575),
 (3886, 0.10206207261596575),
 (4405, 0.10206207261596575),
 (4502, 0.10206207261596575),
 (307, 0.10159281922178943),
 (531, 0.10101525445522105),
 (3405, 0.10101525445522105),
 (4013, 0.10067340828210364),
 (219, 0.10022296571715913),
 (1421, 0.10022296571715913),
 (3044, 0.10022296571715913),
 (3436, 0.10022296571715913),
 (1570, 0.10008009612817945),
 (1579, 0.09999999999999999),
 (167, 0.09847982464479191),
 (400, 0.09847982464479191),
 (590, 0.09847982464479191),
 (781, 0.09847982464479191),
 (1090, 0.09847982464479191),
 (3555, 0.09847982464479191),
 (3361, 0.09805806756909201),
 (4348, 0.09805806756909201),
 (4419, 0.09805806756909201),
 (3210, 0.09752368720068673),
 (248, 0.09712858623572641),
 (1248, 0.09712858623572641),
 (2158, 0.09712858623572641),
 (292, 0.09682458365518541),
 (1077, 0.09682458365518541),
 (1829, 0.09682458365518541),
 (2058, 0.09682458365518541),
 (2737, 0.09682458365518541),
 (3262, 0.09682458365518541),
 (3320, 0.09682458365518541),
 (4270, 0.09682458365518541),
 (4683, 0.09682458365518541),
 (188, 0.09622504486493762),
 (1428, 0.09622504486493762),
 (183, 0.0958706236059213),
 (386, 0.09534625892455922),
 (2444, 0.0953116064578779),
 (28, 0.09525009525014289),
 (260, 0.09525009525014289),
 (579, 0.09525009525014289),
 (678, 0.09525009525014289),
 (794, 0.09525009525014289),
 (960, 0.09525009525014289),
 (1257, 0.09525009525014289),
 (2198, 0.09525009525014289),
 (3888, 0.09525009525014289),
 (4781, 0.09525009525014289),
 (119, 0.0944911182523068),
 (314, 0.0944911182523068),
 (354, 0.0944911182523068),
 (3852, 0.0944911182523068),
 (3947, 0.0944911182523068),
 (2998, 0.09422229518055111),
 (457, 0.09374999999999997),
 (1299, 0.09374999999999997),
 (1427, 0.09374999999999997),
 (2257, 0.09374999999999997),
 (2396, 0.09374999999999997),
 (696, 0.09365858115816939),
 (2350, 0.09365858115816939),
 (425, 0.09284766908852592),
 (750, 0.09284766908852592),
 (3729, 0.09284766908852592),
 (577, 0.09231861823449955),
 (840, 0.09231861823449955),
 (1140, 0.09231861823449955),
 (1612, 0.09231861823449955),
 (1663, 0.09231861823449955),
 (2276, 0.09231861823449955),
 (2935, 0.09231861823449955),
 (4770, 0.09231861823449955),
 (4775, 0.09231861823449955),
 (4432, 0.09205746178983235),
 (1630, 0.09165444688834579),
 (534, 0.09128709291752767),
 (1875, 0.09128709291752767),
 (2149, 0.09128709291752767),
 (2476, 0.09128709291752767),
 (3976, 0.09128709291752767),
 (121, 0.09095085938862485),
 (468, 0.09095085938862485),
 (544, 0.09095085938862485),
 (741, 0.09095085938862485),
 (2202, 0.09095085938862485),
 (4468, 0.09095085938862485),
 (1747, 0.09053574604251853),
 (2435, 0.09053574604251853),
 (67, 0.08964214570007951),
 (72, 0.08964214570007951),
 (512, 0.08964214570007951),
 (985, 0.08964214570007951),
 (1581, 0.08964214570007951),
 (1817, 0.08964214570007951),
 (1838, 0.08964214570007951),
 (2927, 0.08964214570007951),
 (3299, 0.08964214570007951),
 (63, 0.08908708063747478),
 (1362, 0.08908708063747478),
 (1794, 0.08908708063747478),
 (1874, 0.08908708063747478),
 (2102, 0.08908708063747478),
 (4488, 0.08908708063747478),
 (866, 0.08838834764831843),
 (901, 0.08838834764831843),
 (1039, 0.08838834764831843),
 (1197, 0.08838834764831843),
 (1440, 0.08838834764831843),
 (2057, 0.08838834764831843),
 (2861, 0.08838834764831843),
 (3234, 0.08838834764831843),
 (3494, 0.08838834764831843),
 (3525, 0.08838834764831843),
 (3600, 0.08838834764831843),
 (3731, 0.08838834764831843),
 (4568, 0.08838834764831843),
 (51, 0.08770580193070292),
 (2169, 0.08770580193070292),
 (2748, 0.08770580193070292),
 (889, 0.08751750525175062),
 (126, 0.08718572905786445),
 (1481, 0.08718572905786445),
 (1735, 0.08718572905786445),
 (1742, 0.08718572905786445),
 (1754, 0.08718572905786445),
 (3293, 0.08718572905786445),
 (1894, 0.086386842558136),
 (0, 0.08603090020146065),
 (131, 0.08603090020146065),
 (1450, 0.08603090020146065),
 (1544, 0.08603090020146065),
 (2068, 0.08603090020146065),
 (2415, 0.08603090020146065),
 (4076, 0.08603090020146065),
 (47, 0.08574929257125441),
 (153, 0.08574929257125441),
 (186, 0.08574929257125441),
 (1358, 0.08574929257125441),
 (1433, 0.08574929257125441),
 (1460, 0.08574929257125441),
 (1669, 0.08574929257125441),
 (1922, 0.08574929257125441),
 (2776, 0.08574929257125441),
 (2785, 0.08574929257125441),
 (3830, 0.08574929257125441),
 (4229, 0.08574929257125441),
 (4259, 0.08574929257125441),
 (4796, 0.08574929257125441),
 (223, 0.08492077756084468),
 (402, 0.08492077756084468),
 (731, 0.08492077756084468),
 (844, 0.08492077756084468),
 (1013, 0.08492077756084468),
 (1111, 0.08492077756084468),
 (1193, 0.08492077756084468),
 (1896, 0.08492077756084468),
 (2207, 0.08492077756084468),
 (2813, 0.08492077756084468),
 (589, 0.08451542547285165),
 (10, 0.08385254915624211),
 (40, 0.08385254915624211),
 (138, 0.08385254915624211),
 (369, 0.08385254915624211),
 (2682, 0.08385254915624211),
 (4096, 0.08385254915624211),
 (274, 0.0838525491562421),
 (310, 0.0835191380976326),
 (739, 0.08333333333333333),
 (1102, 0.08333333333333333),
 (1137, 0.08333333333333333),
 (1609, 0.08333333333333333),
 (2270, 0.08333333333333333),
 (3079, 0.08333333333333333),
 (3916, 0.08333333333333333),
 (78, 0.0828236445561349),
 (163, 0.0828236445561349),
 (659, 0.0828236445561349),
 (1507, 0.0828236445561349),
 (1519, 0.0828236445561349),
 (1598, 0.0828236445561349),
 (2243, 0.0828236445561349),
 (2373, 0.0828236445561349),
 (2819, 0.0828236445561349),
 (2914, 0.0828236445561349),
 (3399, 0.0828236445561349),
 (3693, 0.0828236445561349),
 (18, 0.0827605888602368),
 (755, 0.0827605888602368),
 (4711, 0.08219949365267865),
 (168, 0.08183170883849714),
 (291, 0.08183170883849714),
 (330, 0.08183170883849714),
 (503, 0.08183170883849714),
 (680, 0.08183170883849714),
 (1909, 0.08183170883849714),
 (2156, 0.08183170883849714),
 (2176, 0.08183170883849714),
 (2446, 0.08183170883849714),
 (2982, 0.08183170883849714),
 (3167, 0.08183170883849714),
 (4043, 0.08183170883849714),
 (800, 0.08111071056538126),
 (914, 0.08111071056538126),
 (993, 0.08111071056538126),
 (1024, 0.08111071056538126),
 (1321, 0.08111071056538126),
 (2331, 0.08111071056538126),
 (2535, 0.08111071056538126),
 (2933, 0.08111071056538126),
 (3075, 0.08111071056538126),
 (3241, 0.08111071056538126),
 (3301, 0.08111071056538126),
 (4064, 0.08111071056538126),
 (4129, 0.08111071056538126),
 (4412, 0.08111071056538126),
 (394, 0.0808745799025788),
 (514, 0.0808745799025788),
 (594, 0.0808745799025788),
 (2932, 0.0808745799025788),
 (3618, 0.0808745799025788),
 (3479, 0.08058229640253801),
 (339, 0.0799502686333539),
 (557, 0.0799502686333539),
 (958, 0.0799502686333539),
 (968, 0.0799502686333539),
 (1107, 0.0799502686333539),
 (1202, 0.0799502686333539),
 (1297, 0.0799502686333539),
 (1467, 0.0799502686333539),
 (1819, 0.0799502686333539),
 (1908, 0.0799502686333539),
 (2348, 0.0799502686333539),
 (3803, 0.0799502686333539),
 (3843, 0.0799502686333539),
 (127, 0.07955572841757301),
 (261, 0.07905694150420949),
 (523, 0.07905694150420949),
 (629, 0.07905694150420949),
 (833, 0.07905694150420949),
 (930, 0.07905694150420949),
 (944, 0.07905694150420949),
 (2010, 0.07905694150420949),
 (3853, 0.07905694150420949),
 (4334, 0.07905694150420949),
 (4531, 0.07905694150420949),
 (179, 0.07905694150420947),
 (200, 0.07905694150420947),
 (627, 0.07905694150420947),
 (653, 0.07905694150420947),
 (858, 0.07905694150420947),
 (924, 0.07905694150420947),
 (1785, 0.07905694150420947),
 (2390, 0.07905694150420947),
 (3139, 0.07905694150420947),
 (3625, 0.07905694150420947),
 (3970, 0.07905694150420947),
 (4160, 0.07905694150420947),
 (4425, 0.07905694150420947),
 (1104, 0.07856742013183861),
 (1452, 0.07856742013183861),
 (412, 0.07819290527140303),
 (870, 0.07819290527140303),
 (872, 0.07819290527140303),
 (1059, 0.07819290527140303),
 (1203, 0.07819290527140303),
 (1827, 0.07819290527140303),
 (2337, 0.07819290527140303),
 (2883, 0.07819290527140303),
 (4081, 0.07819290527140303),
 (426, 0.07808688094430302),
 (1537, 0.07808688094430302),
 (1637, 0.07808688094430302),
 (3737, 0.07808688094430302),
 (4080, 0.07808688094430302),
 (2786, 0.07761505257063328),
 (4, 0.0773565934694095),
 (41, 0.0773565934694095),
 (543, 0.0773565934694095),
 (587, 0.0773565934694095),
 (1271, 0.0773565934694095),
 (2895, 0.0773565934694095),
 (3037, 0.0773565934694095),
 (3702, 0.0773565934694095),
 (490, 0.07715167498104596),
 (613, 0.07715167498104596),
 (1164, 0.07715167498104596),
 (1406, 0.07715167498104596),
 (1472, 0.07715167498104596),
 (2381, 0.07715167498104596),
 (2652, 0.07715167498104596),
 (2960, 0.07715167498104596),
 (2978, 0.07715167498104596),
 (3002, 0.07715167498104596),
 (3418, 0.07715167498104596),
 (4133, 0.07715167498104596),
 (4354, 0.07715167498104596),
 (4783, 0.07715167498104596),
 (182, 0.07654655446197431),
 (444, 0.07654655446197431),
 (574, 0.07654655446197431),
 (767, 0.07654655446197431),
 (788, 0.07654655446197431),
 (1138, 0.07654655446197431),
 (1688, 0.07654655446197431),
 (2324, 0.07654655446197431),
 (4795, 0.07654655446197431),
 (97, 0.07576144084141578),
 (243, 0.07576144084141578),
 (611, 0.07576144084141578),
 (782, 0.07576144084141578),
 (1001, 0.07576144084141578),
 (1442, 0.07576144084141578),
 (233, 0.0753778361444409),
 (657, 0.0753778361444409),
 (1325, 0.0753778361444409),
 (1677, 0.0753778361444409),
 (2319, 0.0753778361444409),
 (2517, 0.0753778361444409),
 (3350, 0.0753778361444409),
 (3619, 0.0753778361444409),
 (3837, 0.0753778361444409),
 (4290, 0.0753778361444409),
 (4303, 0.0753778361444409),
 (419, 0.075),
 (600, 0.075),
 (1218, 0.075),
 (1283, 0.075),
 (2239, 0.075),
 (665, 0.07426106572325056),
 (758, 0.07426106572325056),
 (1125, 0.07426106572325056),
 (1414, 0.07426106572325056),
 (3308, 0.07426106572325056),
 (4538, 0.07426106572325056),
 (209, 0.07372097807744857),
 (308, 0.07372097807744857),
 (476, 0.07372097807744857),
 (505, 0.07372097807744857),
 (1150, 0.07372097807744857),
 (1224, 0.07372097807744857),
 (1540, 0.07372097807744857),
 (1856, 0.07372097807744857),
 (2113, 0.07372097807744857),
 (2618, 0.07372097807744857),
 (3084, 0.07372097807744857),
 (3393, 0.07372097807744857),
 (3588, 0.07372097807744857),
 (3659, 0.07372097807744857),
 (3674, 0.07372097807744857),
 (3896, 0.07372097807744857),
 (3980, 0.07372097807744857),
 (4214, 0.07372097807744857),
 (4285, 0.07372097807744857),
 (83, 0.073543550676819),
 (123, 0.073543550676819),
 (140, 0.073543550676819),
 (702, 0.073543550676819),
 (1431, 0.073543550676819),
 (3339, 0.073543550676819),
 (3387, 0.073543550676819),
 (30, 0.07284643967679481),
 (158, 0.07284643967679481),
 (582, 0.07284643967679481),
 (735, 0.07284643967679481),
 (777, 0.07284643967679481),
 (1744, 0.07284643967679481),
 (2347, 0.07284643967679481),
 (2407, 0.07284643967679481),
 (3412, 0.07284643967679481),
 (3506, 0.07284643967679481),
 (4694, 0.07284643967679481),
 (35, 0.07216878364870323),
 (61, 0.07216878364870323),
 (157, 0.07216878364870323),
 (162, 0.07216878364870323),
 (201, 0.07216878364870323),
 (237, 0.07216878364870323),
 (604, 0.07216878364870323),
 (715, 0.07216878364870323),
 (1053, 0.07216878364870323),
 (1075, 0.07216878364870323),
 (1490, 0.07216878364870323),
 (2074, 0.07216878364870323),
 (2240, 0.07216878364870323),
 (2374, 0.07216878364870323),
 (2580, 0.07216878364870323),
 (3465, 0.07216878364870323),
 (4593, 0.07216878364870323),
 (215, 0.07216878364870322),
 (228, 0.07216878364870322),
 (270, 0.07216878364870322),
 (645, 0.07216878364870322),
 (1110, 0.07216878364870322),
 (304, 0.07169241683455055),
 (396, 0.07150969419341942),
 (694, 0.07150969419341942),
 (1646, 0.07150969419341942),
 (1954, 0.07150969419341942),
 (2129, 0.07150969419341942),
 (2131, 0.07150969419341942),
 (3456, 0.0708683386892301),
 (5, 0.07086833868923009),
 (33, 0.07071067811865475),
 (109, 0.07071067811865475),
 (216, 0.07071067811865475),
 (368, 0.07071067811865475),
 (1434, 0.07071067811865475),
 (1482, 0.07071067811865475),
 (1558, 0.07071067811865475),
 (1783, 0.07071067811865475),
 (2063, 0.07071067811865475),
 (2227, 0.07071067811865475),
 (2306, 0.07071067811865475),
 (2575, 0.07071067811865475),
 (2880, 0.07071067811865475),
 (3334, 0.07071067811865475),
 (3372, 0.07071067811865475),
 (3556, 0.07071067811865475),
 (3854, 0.07071067811865475),
 (4476, 0.07071067811865475),
 (983, 0.07035975447302918),
 (746, 0.07024393586862704),
 (1153, 0.07024393586862704),
 (2138, 0.06967330142916177),
 (262, 0.06963575181639443),
 (507, 0.06963575181639443),
 (1729, 0.06963575181639443),
 (2523, 0.06963575181639443),
 (31, 0.06933752452815364),
 (290, 0.06933752452815364),
 (487, 0.06933752452815364),
 (495, 0.06933752452815364),
 (561, 0.06933752452815364),
 (791, 0.06933752452815364),
 (1042, 0.06933752452815364),
 (1419, 0.06933752452815364),
 (1850, 0.06933752452815364),
 (2224, 0.06933752452815364),
 (2459, 0.06933752452815364),
 (2504, 0.06933752452815364),
 (2560, 0.06933752452815364),
 (3131, 0.06933752452815364),
 (3146, 0.06933752452815364),
 (3419, 0.06933752452815364),
 (3591, 0.06933752452815364),
 (3855, 0.06933752452815364),
 (3909, 0.06933752452815364),
 (4297, 0.06933752452815364),
 (4355, 0.06933752452815364),
 (4433, 0.06933752452815364),
 (48, 0.06904309634237427),
 (273, 0.06904309634237427),
 (305, 0.06904309634237427),
 (1279, 0.06904309634237427),
 (1458, 0.06904309634237427),
 (1492, 0.06904309634237427),
 (3738, 0.06904309634237427),
 (4647, 0.06904309634237427),
 (15, 0.06846531968814575),
 (253, 0.06846531968814575),
 (591, 0.06846531968814575),
 (873, 0.06846531968814575),
 (1120, 0.06846531968814575),
 (2494, 0.06846531968814575),
 (3605, 0.06846531968814575),
 (202, 0.06804138174397717),
 (433, 0.06804138174397717),
 (660, 0.06804138174397717),
 (920, 0.06804138174397717),
 (1047, 0.06804138174397717),
 (1156, 0.06804138174397717),
 (1387, 0.06804138174397717),
 (1682, 0.06804138174397717),
 (1939, 0.06804138174397717),
 (2338, 0.06804138174397717),

In [149]:
# fetching top 5 movies
sorted(list(enumerate(similarity[2])),reverse=True,key=lambda x:x[1])[1:6]

[(11, 0.3609974361905776),
 (29, 0.3307189138830738),
 (1344, 0.32639560491693337),
 (4075, 0.2611164839335467),
 (1745, 0.2390457218668787)]

## Now to implement all these functionalities discussed above, we will create a function

In [156]:
# function which takes movie as an input and returns 5 similar movies
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)     # new_df.iloc[i[0]].title will fetch 5 movies name from the data. i[0] will give the top 5 movies index and corresponding to that index we will fetch the movie name

In [157]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [160]:
recommend('The Avengers')

Iron Man 3
Avengers: Age of Ultron
Captain America: Civil War
Captain America: The First Avenger
Iron Man

In [161]:
recommend('Batman')

Batman
Batman & Robin
Batman Begins
Batman Returns
The R.M.

In [162]:
import pickle

In [165]:
pickle.dump(new_df.to_dict(),open('movies-recommender/movie_dict.pkl','wb'))

In [166]:
pickle.dump(similarity,open('movies-recommender/similarity.pkl','wb'))